### ISSUE TITLE
Add test cases for add.py

### ISSUE THREAD

**Issue by sak007** [sak007/MyDollarBot#13]
Write tests for the app.py functionality.

**Comment by wizard-31** [comment]
Test cases work and build passes. Good to close the issue.

**Comment by wizard-31** [comment]
Re-opening as branch is yet to be merged with main.

**Comment by sak007** [comment]
Coverage is only 70% Try u add some test cases for post_amount_input(message, bot)
https://app.codecov.io/gh/sak007/MyDollarBot/blob/backlogs/code/add.py

**Comment by sak1997** [comment]
Fixed now. 

Additional Test cases added, older issues have been fixed. There was an issue with build failing, and that has been cleared up as well. Commit 901360f74d476e22814ea21e3fec01fa09a401b6

Please verify and confirm.
