### ISSUE TITLE
Build Failed - Please fix styling and linting issues

### ISSUE THREAD

**Issue by sak1997** [sak007/MyDollarBot#15]
Please fix the issues with the latest commit - build is failing, so need to fix this.

Problematic Commit 668268cd8c5bf686fc83b66d5012ee57d482714f

**Comment by sak1997** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Studies\\Masters - NCSU - Course wise\\CSC510 - Software Engg\\Project-2\\MyDollarBot\\test'

Issue noted on Travis

**Comment by wizard-31** [comment]
Updated the Styling issues and Style Checkers - 134544d20b15bc493ee7d5703259fce1d3bf7e18
Build passing and test cases updated

**Comment by wizard-31** [comment]
@sak1997 @sak007  - Please review and close the issue, if satisfactory.
