### ISSUE TITLE
Add test cases for history.py

### ISSUE THREAD

**Issue by sak007** [sak007/MyDollarBot#9]

**Comment by sak007** [comment]
Build is failing https://app.travis-ci.com/github/sak007/MyDollarBot/builds/240895751
Don't hardcode path

**Comment by wizard-31** [comment]
Updated the Styling issues and Style Checkers - 134544d20b15bc493ee7d5703259fce1d3bf7e18
Build passing and test cases updated for delete.py and history.py

Please verify the close the issue if there are no more errors. @sak007 @sak1997

**Comment by wizard-31** [comment]
Updated the Styling issues and Style Checkers - 134544d20b15bc493ee7d5703259fce1d3bf7e18
Build passing and test cases updated for delete.py and history.py

Please verify the close the issue if there are no more errors. @sak1997  @sak007
